//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ECQPS.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_MODULENAME                  109
#define IDS_MODULEVER                   110
#define IDS_MODULEVENDOR                111
#define IDS_MODULECTIME                 112
#define IDS_MODULEMTIME                 113
#define IDS_MODULEPATH                  114
#define IDS_PERM_CPU                    115
#define IDS_PERM_MEM                    116
#define IDS_PERM_DISK                   117
#define IDS_PERM_CACHE                  118
#define IDS_NETWORK_SRC                 119
#define IDS_NETWORK_SP                  120
#define IDS_NETWORK_DES                 121
#define IDS_NETWORK_DP                  122
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    128
#define IDR_ECQPSTYPE                   129
#define IDB_ARROWDOWN                   130
#define IDB_ARROWUP                     131
#define IDB_BLANK                       132
#define IDB_BITMAP4                     137
#define IDB_LIST_LARGE_IMAGES           140
#define IDB_BITMAP6                     141
#define IDB_BITMAP7                     143
#define IDB_BITMAP8                     144
#define IDB_BITMAP10                    146
#define IDB_BITMAP_XPMENU               146
#define IDB_LIST_SMALL_IMAGES           148
#define IDB_BITMAP_SYS_TRAY             149
#define IDI_ICON_UNKNOWN                151
#define IDI_ICON_SUSPICON               152
#define IDI_ICON2                       153
#define IDI_ICON_ALLMODULE              154
#define IDI_ICON_PROPERT                155
#define IDI_ICON_PEINFO                 156
#define IDI_ICON_PERFOR                 157
#define IDR_MENULBAR                    159
#define IDR_POPMENU                     161
#define IDR_TRAYMENU                    163
#define IDB_POPMENU_OPEN                166
#define IDB_POPMENU_AUTOKILL            167
#define IDR_POPMENUBAR                  168
#define IDD_DLGSERVICE                  170
#define IDD_DLGREGBOOT                  171
#define IDD_DLGWARNING                  172
#define IDI_WARING                      173
#define IDB_DLGWARNING_BK               174
#define IDB_DLGWARNING_OK               175
#define IDB_DLGWARNING_CANCEL           176
#define IDB_DLGBOUT_BK                  177
#define IDB_DLGBOUT_MAIL                178
#define IDB_DLGBOUT_WEB                 179
#define IDB_BOLOON_BK                   180
#define IDR_POPMENUML                   182
#define IDD_DLGMODULELK                 183
#define IDI_ICON_LOCKED                 184
#define IDI_ICON_SAFE                   187
#define IDI_ICON_VIRUS                  188
#define IDI_ICON_NOTION                 189
#define IDI_ICON_PROM                   190
#define IDS_PROCESSNAME                 202
#define IDS_PROCESSID                   203
#define IDS_PROCESSWARN                 204
#define IDS_PROCESSPRORITY              205
#define IDS_PROCESSTHREAD               206
#define IDS_PROCESSCRTIME               207
#define IDS_PROCESSPATH                 208
#define IDS_PROCESSINFO                 209
#define IDC_LISTSERVICE                 1000
#define IDC_SERVICE_RERFRSH             1001
#define IDC_SERVICE_DELETE              1002
#define IDC_SERVICE_DRIVER              1003
#define IDC_SERVICE_ALL                 1004
#define IDC_REGBOOT_LIST                1005
#define IDC_REGBOOT_DELETE              1006
#define IDC_DLGWARNING_INFO             1007
#define IDC_DLGMODULE_DELETE            1010
#define IDC_MODULE_LIST                 1011
#define IDC_DLGMODULE_NAME              1012
#define ID_VIEW_INFO_BAR                32771
#define ID_VIEW_MODULE_BAR              32772
#define ID_POPMENU_AUTOKILL             32780
#define ID_BUTTON32787                  32787
#define ID_MAINMENU_TOP                 32793
#define ID_POPML_OPEN                   32797
#define ID_POPML_COPY                   32798
#define ID_ACCEL32799                   32799
#define ID_MENUITEM32800                32800
#define ID_MENUITEM32801                32801
#define ID_MENU_DISABLEDAUTO            32802
#define ID_TOOL_REFRESHE                50000
#define ID_TOOL_NETWORK                 50001
#define ID_TOOL_PERFORMANCE             50002
#define ID_TOOL_SERVICE                 50003
#define ID_TOOL_BOOT                    50004
#define ID_TOOL_COMPUTEE                50005
#define ID_TOOL_NOTPAD                  50006
#define ID_TOOL_HOME                    50007
#define ID_TOOL_HELP                    50008
#define ID_TOOL_ABOUT                   50009
#define ID_TOOL_KILL                    50010
#define ID_TOOL_REGEDIT                 50011
#define ID_TOOL_CONSOLE                 50012
#define ID_TOOL_NORMAL                  50013
#define ID_MENU_REFRESHE                50100
#define ID_MENU_NETWORK                 50101
#define ID_MENU_PERFORMANCE             50102
#define ID_MENU_SERVICE                 50103
#define ID_MENU_BOOT                    50104
#define ID_MENU_COMPUTEE                50105
#define ID_MENU_NOTPAD                  50106
#define ID_MENU_HOME                    50107
#define ID_MENU_HELP                    50108
#define ID_MENU_ABOUT                   50109
#define ID_MENU_KILL                    50110
#define ID_MENU_REGEDIT                 50111
#define ID_MENU_CONSOLE                 50112
#define ID_MENU_NORMAL                  50113
#define ID_POPMENU_KILL                 50211
#define ID_POPMENU_OPEN                 50212
#define ID_POPMENU_COPY                 50213
#define ID_POPMENU_HELP                 50214
#define ID_POPMENU_DELETE               50215
#define ID_INDICATOR_UPTIME             61204
#define ID_INDICATOR_NORMAL             61205
#define ID_TOOL_HIDDEN                  61206
#define IDS_ROOTKITSYS_NO               61206
#define IDS_ROOTKITSYS_AD               61207
#define IDS_ROOTKITSYS_SIZE             61208
#define IDS_ROOTKITSYS_HID              61209
#define IDS_ROOTKITSYS_NAME             61210

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
